command: ['flask', '--app', 'app.py', 'run', '--host', '0.0.0.0', '--port', '8000']

env:
  - name: PGHOST
    value: '<your-endpoint-hostname>'        # from Lakebase "Connect" modal
  - name: PGDATABASE
    value: 'databricks_postgres'
  - name: PGUSER
    value: '165adb1d-51e4-4644-a03f-1aedb627b206'          # app's Environment tab, after creation
  - name: PGPORT
    value: '5432'
  - name: PGSSLMODE
    value: 'require'
  - name: ENDPOINT_NAME
    value: 'projects/<project-id>/branches/<branch-id>/endpoints/<endpoint-id>'
